### ISSUE TITLE
Type checking

### ISSUE THREAD

**Issue by CoolCat467** [jorio/gitfourchette#2]
I noticed that running mypy (https://github.com/python/mypy) on this project shows a bunch of type errors, and I was wondering if you would be interested in accepting a pull request wherein I add type annotations/fix type issues in this project.

Checking your code with a static type analyzer like mypy can help catch potential runtime issues before they happen. A common parallel I have heard is that type checkers are like linters (such as ruff) on steroids.

Additionally, adding typing information can help other developers (or yourself) understand your code and what types of data should be where. It also opens the door to potentially using [mypyc](https://mypyc.readthedocs.io/en/latest/introduction.html) on this project, meaning code could be compiled into c-based modules that can in some cases run significantly more efficiently, but that would be something for later.

**Comment by jorio** [comment]
Thank you for the offer! Unfortunately, it looks like mypy isn't very usable with PyQt6 (I couldn't get it to recognize PySide6's types).

For instance, it complains that the None part is ignored in many `QSomeType | None` unions that abound in PyQt6's type stubs. I suspect these stubs were automatically generated with the assumption that whenever a C++ function in Qt takes a pointer, it can technically be NULL, so this should auto-translate to `| None`; but this is impractical for writing GUI code in Python.

There are surely inaccuracies in this project's type annotations, but I'd prefer to fix them on a case-by-case basis, rather than adding a lot of boilerplate at once to comply with mypy's enforcement of PyQt6's auto-generated type annotations. Until then, thorough test coverage is our main tool for ironing out runtime issues.

**Comment by Genfood** [comment]
I would like to double down on Type checking.

I saw a few places where proper typing was simply missing, methods which return unknown, instead of at least a QWidget type.

I know it's also a preference, but I guess proper typing makes the life much easier.

Also there are community driven stubs packages, which improve typing support a lot:
- https://pypi.org/project/PySide6-stubs/
- https://github.com/python-qt-tools/PyQt6-stubs

Furthermore, it is worth mentioning that strict None type checking can be disabled, in `mypy`.

```python
[tool.mypy]
strict_optional = false
```

Maybe, it is worth thinking about it again?

**Comment by jorio** [comment]
I gave it another go with this config:

```toml
[tool.mypy]
strict_optional = false

# NOTE: trimming error list to most serious errors just to get started.
# In the future, don't disable any error codes and fix them all?
disable_error_code = ["var-annotated", "assignment", "attr-defined"]

[[tool.mypy.overrides]]
module = ["gitfourchette.qt", "gitfourchette.pycompat"]
ignore_errors = true

```

I also forced mypy to stick to PyQt6 only by modifying the imports in qt.py like so:

```python
if _tentative == "pyside6" and not _typing.TYPE_CHECKING:  # --- edited
    ...
elif _tentative == "pyqt6":  # --- keep intact
    ...
elif _tentative == "pyqt5" and not _typing.TYPE_CHECKING:  # --- edited
    ...
```

This results in a much more manageable error count than before. Some errors look sensible, so I'll consider cleaning them up. If I can get to 0 errors, we can add a mypy step to CI.
